#!/bin/sh
#
# Start/stop tonio
#

TONIO=/usr/bin/tonio
PIDFILE=/var/run/tonio.pid

case "$1" in
  start)
	echo "Starting tonio..."
	mkdir -p /usr/share/tonio
        amixer cset numid=3 1
	start-stop-daemon -S -x "$TONIO" -b -m -p "$PIDFILE"
	;;
  stop)
	echo "Stopping tonio..."
	start-stop-daemon -K -x "$TONIO" -p "$PIDFILE" -o
	;;
  restart)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
