name: Build supported images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-supported-images:

    runs-on: ubuntu-latest
    
    strategy:
        matrix:
            config: [raspberrypi3]
            version:
              - label: LTS
                value: "2025.02.15"
              - label: stable
                value: "2026.05"

    steps:
        
    - uses: actions/checkout@v4
            
    - name: Setup Buildroot ccache
      uses: actions/cache@v3
      with:
        path: ~/.buildroot-ccache
        key: buildroot-${{ matrix.version.value }}-${{ matrix.config }}-ccache
    
    - name: Setup Buildroot downloads cache
      uses: actions/cache@v4
      with:
        path: ~/.buildroot-dl
        key: buildroot-dl
        
    - name: Prepare environment
      run: |
        wget https://buildroot.org/downloads/buildroot-${{ matrix.version.value }}.tar.gz
        tar xzf buildroot-${{ matrix.version.value }}.tar.gz
        sudo apt-get update
        sudo apt-get install graphviz python3-matplotlib
        
    - name: Build Images
      run: |
        cd buildroot-${{ matrix.version.value }}
        export BR2_DL_DIR=~/.buildroot-dl
        make BR2_EXTERNAL=../ tonio_${{ matrix.config }}_defconfig
        make
    
    - name: Upload Images
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.config }}-${{ matrix.version.label }} images
        path: |
            buildroot-${{ matrix.version.value }}/output/images
            board/${{ matrix.config }}/flash.sh
                
    - name: Build Graphs
      run: |
        cd buildroot-${{ matrix.version.value }}
        make graph-size
        make graph-depends
        make graph-build

    - name: Upload Graphs
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.config }}-${{ matrix.version.label }} graphs
        path: 'buildroot-${{ matrix.version.value }}/output/graphs'

