name: Tonio build and test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:plucky
    strategy:
      matrix:
        media: [vlc, opus]
    steps:
      - name: Install dependencies
        run: |
          apt-get -y update
          apt-get -y install git libvlc-dev libopusfile-dev libasound2-dev libconfuse-dev libgpiod-dev libmicrohttpd-dev libiw-dev check build-essential cmake pkg-config tree
      - uses: actions/checkout@v4
      - name: Configure (${{ matrix.media }})
        run: |
          cmake -S package/tonio/tonio-1.0 -B package/tonio/tonio-1.0/_build \
            -DCMAKE_INSTALL_PREFIX= \
            -DMEDIA_BACKEND=${{ matrix.media }}
      - name: Build (${{ matrix.media }})
        run: |
          cmake --build package/tonio/tonio-1.0/_build
      - name: Install to ~/tmp and Inspect (${{ matrix.media }})
        run: |
          cmake --install package/tonio/tonio-1.0/_build --prefix ~/tmp --strip
          tree ~/tmp
      - name: Run Unit Tests (${{ matrix.media }})
        run: |
          cd package/tonio/tonio-1.0/_build
          ctest --output-on-failure --verbose
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: tonio-test-${{ matrix.media }}
          path: package/tonio/tonio-1.0/_build/tests/*


        
